for x in reversed(range(3)):   
    print("float3 ray_color" + str(x) + "(ray r, hittable_list world, int depth, int x, int y, int z){")
    print("    hit_record rec;")
    print("    if(depth <= 0){")
    print("        return float3(0,0,0);")
    print("    }")
    print("    if (world.hit(r, 0, 1000, rec)) {")
    print("        float3 target = rec.p + rec.normal + random_in_unit_sphere(x, y, z);")
    print("        return 0.5 * ray_color"+ str(x+1) + "(ray(rec.p, target - rec.p), world, (depth - 1), (x*2), (y*2), (z*2));")
    print("    }")
    print("    half3 unit_dir = half3(unit_vector(r.direction));")
    print("    auto t = 0.5*(unit_dir.y + 1.0);")
    print("    return ((1-t)*float3(1.0,1.0,1.0) + t*float3(0.5, 0.7, 1.0));")
    print("}")